---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: svm-latex-cv.tex
geometry: margin=1in

title: "CV"
author: Eric Hare

jobtitle: "Chief Data Scientist at Omni Analytics Group"
address: "2405 Grant Cir, Ames, IA, 50010"
fontawesome: yes
email: eric@omnianalytics.io
github: erichare
phone: "+1-425-405-0279"
web: erichare.me
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Research Interests

Exploratory Data Analysis, Statistical Graphics, Statistical Computing, Reproducible Research, Graphical User Interfaces, Statistical Forensics

# Education

## Iowa State University

Doctor of Philosophy in Statistics & Computer Science \hfill Received May 2017

Master of Science in Statistics \hfill Received May 2014

## University of Washington

Bachelor of Science with a Major in Statistics, Cum Laude \hfill Received June 2012

Bachelor of Science in Computer Engineering, Cum Laude \hfill Received June 2012

# Publications

Hare, E., Hofmann, H., and Carriquiry, A., **A Modern Bullet Matching Database and Web Application**. In Progress

Hare, E., Hofmann, H., and Carriquiry, A., **Algorithmic Approaches to Bullet Matching with an Emphasis on the Degraded Land Case**. In Progress

Hare, E., Hofmann, H., and Carriquiry, A., **Automatic Matching of Bullet Lands**. In Progress

Hare, E., and Kaplan, A., **Designing Modular Software: A Case Study in Introductory Statistics**. Accepted by the Journal of Computational and Graphical Statistics

Dao, B., Kermanshachi, S., Shane, J., Anderson, S., and Hare, E., **Exploring and Assessing Project Complexity**.  Journal of Construction Engineering and Management: 04016126 (2016)

Hare, E., Buja, A., and Hofmann, H., **Manipulation of Discrete Random Variables with discreteRV**. R Journal Vol. 7 Iss. 1 (2015)

Sieber, T., Hare, E., Hofmann, H., and Treppel, M., **Biomathematical description of synthetic Peptide libraries**. PLOS One Vol. 10 Iss. 6 (2015)

Kaplan, A., and Hare, E., Putting Down Roots: **A Graphical Exploration of Community Attachment** (Accepted in Computational Statistics)

Kaplan, A., Hare, E., Hofmann, H., and Cook, D., **Can you buy a president? Politics after the Tillman Act**. CHANCE Vol. 27 Iss. 1 (2014)

# Posters & Presentations

Hare. E., **Reproducing User Actions in Shiny**. Shiny Developer Conference, Jan 30-31, 2016, Palo Alto, CA, USA

Hare, E., Kaplan, A., **intRo: Statistical Analysis Software for Teaching**. Contributed Paper, Joint Statistical Meetings, Aug 8-13, 2015, Seattle, WA, USA

Hare, E., Buja, A., and Hofmann, H., **Manipulation of Discrete Random Variables in R with discreteRV**. useR, Jul 2, 2015, Aalborg, DK

Cook, D., Hare, E., **ASA Traveling Workshops**, May 15-18, 2015, UCLA, Chapman University, Pfizer, California, USA

Hare, E., Kaplan, A., **intRo: Statistical Analysis Software for Teaching**. Departmental Seminar (Iowa State University), Jan 12, 2015, Ames, IA, USA

Hare, E., Sieber, T., and Hofmann, H., **A Web Application for Efficient Analysis of Peptide Libraries**. Contributed Paper, Joint Statistical Meetings, Aug 2-7, 2014, Boston, MA, USA

Kaplan, A., and Hare, E., **Putting Down Roots: A Graphical Exploration of Community Attachment**. Census Data Visualization Seminar, US Census Bureau, Sep 19, 2013, Washington, D.C., USA

Hare, E., Kaplan, A., Hofmann, H., and Cook, D., **Can you buy a president? Politics after the Tillman Act**. Poster Presentation, Joint Statistical Meetings, Aug 3-8, 2013, Montreal, QC

Kaplan, A., and Hare, E., Putting Down Roots: **A Graphical Exploration of Community Attachment**. Poster Presentation, Joint Statistical Meetings, Aug 3-8, 2013, Montreal, QC

# Awards

ASA Imaging Section Student Paper Award \hfill Received 2016

Ron Wasserstein Award for Best Contributed Paper in Statistical Education \hfill Received 2015

ASA Computing Section Student Paper Award \hfill Received 2015

Kempthorne Award for Best Student in Linear Models \hfill Received 2013

ASA Data Exposition - 1st Place \hfill Received 2013

# Academic Experience

## Instructor

Engineering Probability (STAT 231). Prepared syllabus, lectures, exams, course notes, homeworks, and held office hours. Responsible for 40 students.

Introduction to Business Statistics (STAT 226). Prepared lectures, exams, helped prepare course notes, homeworks, and held office hours. Responsible for 80 students.

## Teaching Assistant

Engineering Statistics (STAT 305). Held office hours, graded homeworks and exams.

Empirical Methods for Computer Science (STAT 430). Held office hours, graded homeworks.

Applied Statistical Computing (STAT 480). Held office hours, graded homeworks.

Introduction to Statistical Computing (STAT 579). Held office hours, graded homeworks, assisted in creation of exams.

## Research Assistant

Analyzed bullet striation patterns for the Center for Statistics and Applications in Forensic Evidence (CSAFE) (Hofmann, H., Carriquiry, A.)

Explored the Lineup Protocol in visual inference. Modified an automated framework for performing tests of significance with the lineup protocol, assisted others in performing experiments, with Hofmann, H., Cook, D.

Developed statistical models and graphical summaries for Shane, J.

Developed an automated hand-tracking mechanism using OpenCV and Python to independently track two hands using a camera connected to a computer. Worked with Fox, D.

## Work Experience

Chief Data Scientist, Omni Analytics Group \hfill May 2017 - Present

Data Scientist, Omni Analytics Group \hfill Aug 2014 - May 2017

Research Assistant, Iowa State University \hfill Aug 2015 - May 2017

Teaching Assistant, Iowa State University \hfill Aug 2012 - Aug 2015

Quality Assurance Intern, TIBCO Software, Inc. \hfill Jun 2010 - Aug 2013

# References

References available upon request.
